# ml/train_sequence.py - Sequence training pipeline for Phase 5
import os
import argparse
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Subset

from sequence_models import WavefrontLSTM, TurbulenceClassifierLSTM, TurbulenceParameterEstimator, SlopeCompletionLSTM

def check_split_leakage(dataset, train_indices, val_indices, test_indices):
    """
    Assert that no sequence ID appears in more than one split.
    Must be called after SHSequenceDataset is constructed.
    """
    def seq_ids(indices):
        return set(dataset.sequence_ids[i] for i in indices)
    train_s = seq_ids(train_indices)
    val_s = seq_ids(val_indices)
    test_s = seq_ids(test_indices)
    tv = train_s & val_s
    tt = train_s & test_s
    vt = val_s & test_s
    if tv or tt or vt:
        raise AssertionError(
            f"Temporal leakage detected: train↔val {len(tv)}, "
            f"train↔test {len(tt)}, val↔test {len(vt)} sequences overlap."
        )

class SHSequenceDataset(Dataset):
    """
    Sequence dataset loader that slices sequence frames into sliding windows
    without crossing sequence boundaries (each sequence is 1000 frames).

    Splits should be performed at the *sequence* level (see split_by_sequence())
    to avoid temporal leakage from adjacent overlapping windows.

    For the 'complete_slopes' task, each sample contains:
        x: [lookback+1, 4*nspots]  tensor of observed slopes + masks
        y: [lookback+1, 2*nspots]  tensor of clean (unmasked) slopes
    where the last time step is the partially observed current frame and the
    preceding lookback steps provide temporal context.  The mask is available
    in x[:, 2*nspots:] and in y to drive the masked reconstruction loss.
    """
    def __init__(self, dataset_path, lookback=10, step=1, task='predict'):
        self.lookback = lookback
        self.step = step
        self.task = task

        # Load dataset
        data = np.load(dataset_path)
        displacements = data['displacements']
        coefficients = data['coefficients']
        D_r0 = data['D_r0']

        # Optional: masked observations generated by generate_dataset.py
        if 'masks' in data:
            masks = data['masks']
        else:
            masks = None

        n_frames = len(displacements)
        self.seq_len = 1000
        n_sequences = n_frames // self.seq_len
        nspots = displacements.shape[1] // 2

        self.samples = []
        self.sequence_ids = []
        for s in range(n_sequences):
            seq_start = s * self.seq_len

            # Slice sequence data
            seq_disp = displacements[seq_start : seq_start + self.seq_len]
            seq_coeff = coefficients[seq_start : seq_start + self.seq_len]
            seq_dr0 = D_r0[seq_start : seq_start + self.seq_len]
            if masks is not None:
                seq_mask = masks[seq_start : seq_start + self.seq_len]
            else:
                seq_mask = None

            # Determine classification class based on average D_r0 of sequence
            avg_dr0 = float(np.mean(seq_dr0))
            if avg_dr0 < 3.0:
                class_idx = 0  # Weak
            elif avg_dr0 < 7.0:
                class_idx = 1  # Moderate
            else:
                class_idx = 2  # Strong

            # Sliding windows within sequence
            for t in range(self.lookback, self.seq_len - self.step + 1):
                # Input history: L frames
                hist_coeff = seq_coeff[t - self.lookback : t]
                hist_disp = seq_disp[t - self.lookback : t]

                if self.task == 'predict':
                    # Target: coefficients at t + step - 1
                    target = seq_coeff[t + self.step - 1]
                    self.samples.append((hist_coeff, target))
                elif self.task == 'classify':
                    # Target: class index based on sequence turbulence strength
                    self.samples.append((hist_coeff, class_idx))
                elif self.task == 'parameter':
                    # Target: average D_r0 of sequence
                    self.samples.append((hist_disp, avg_dr0))
                elif self.task == 'complete_slopes':
                    # Window of L past frames + current frame
                    window_disp = seq_disp[t - self.lookback : t + 1]
                    if seq_mask is not None:
                        window_mask = seq_mask[t - self.lookback : t + 1]
                    else:
                        # All valid if no pre-generated masks
                        window_mask = np.ones((self.lookback + 1, 2 * nspots), dtype=np.float32)
                    # x stores the full window for the LSTM, but y is just the
                    # *current* frame so the model predicts only s_t.
                    x = np.concatenate([window_disp * window_mask, window_mask], axis=1)
                    current_clean = window_disp[-1]
                    current_mask = window_mask[-1]
                    y = np.concatenate([current_clean, current_mask])
                    self.samples.append((x, y))
                self.sequence_ids.append(s)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        x, y = self.samples[idx]
        if self.task == 'classify':
            return torch.tensor(x, dtype=torch.float32), torch.tensor(y, dtype=torch.long)
        else:
            return torch.tensor(x, dtype=torch.float32), torch.tensor(y, dtype=torch.float32)
    
    @staticmethod
    def split_by_sequence(dataset, train_ratio=0.8, val_ratio=0.1, seed=42):
        """
        Split dataset by contiguous blocks of sequences (not individual samples).
        This avoids temporal leakage from adjacent overlapping windows.
        
        Returns (train_set, val_set, test_set) as torch Subset instances.
        """
        n_seqs = max(dataset.sequence_ids) + 1 if dataset.sequence_ids else 0
        seq_indices = list(range(n_seqs))
        rng = np.random.RandomState(seed)
        rng.shuffle(seq_indices)

        n_train = int(round(train_ratio * n_seqs))
        n_val = int(round(val_ratio * n_seqs))
        n_test = n_seqs - n_train - n_val
        # Guarantee at least one sequence in each split when possible.
        if n_seqs >= 3:
            if n_val == 0:
                n_val = 1
                n_train = max(1, n_train - 1)
            if n_test == 0:
                n_test = 1
                n_train = max(1, n_train - 1)
        elif n_seqs == 2:
            n_train, n_val, n_test = 1, 1, 0
        else:
            n_train, n_val, n_test = n_seqs, 0, 0

        train_seqs = set(seq_indices[:n_train])
        val_seqs = set(seq_indices[n_train:n_train + n_val])
        test_seqs = set(seq_indices[n_train + n_val:])
        
        train_idx = [i for i, sid in enumerate(dataset.sequence_ids) if sid in train_seqs]
        val_idx   = [i for i, sid in enumerate(dataset.sequence_ids) if sid in val_seqs]
        test_idx  = [i for i, sid in enumerate(dataset.sequence_ids) if sid in test_seqs]
        
        check_split_leakage(dataset, train_idx, val_idx, test_idx)
        
        return (Subset(dataset, train_idx),
                Subset(dataset, val_idx),
                Subset(dataset, test_idx))


def train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    n_total = 0
    for inputs, targets in loader:
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)

        # Squeeze output if doing 1D parameter estimation regression
        if outputs.dim() > 1 and targets.dim() == 1:
            outputs = outputs.squeeze(1)

        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        n_total += inputs.size(0)
    return running_loss / n_total if n_total > 0 else 0.0





def train_epoch_complete(model, loader, criterion, optimizer, device):
    """Training loop for the slope completion task."""
    model.train()
    running_loss = 0.0
    n_total = 0
    for inputs, targets in loader:
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss, _, _ = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        n_total += inputs.size(0)
    return running_loss / n_total if n_total > 0 else 0.0


def evaluate(model, loader, criterion, device, task='predict'):
    model.eval()
    running_loss = 0.0
    n_total = 0
    with torch.no_grad():
        for inputs, targets in loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)

            if outputs.dim() > 1 and targets.dim() == 1:
                outputs = outputs.squeeze(1)

            if task == 'complete_slopes':
                loss, _, _ = criterion(outputs, targets)
            else:
                loss = criterion(outputs, targets)
            running_loss += loss.item() * inputs.size(0)
            n_total += inputs.size(0)
    return running_loss / n_total if n_total > 0 else 0.0


def run_persistence_baseline(loader, step):
    """
    Evaluate the persistence baseline MSE on the test loader.
    Persistence predicts a_future = a_current (i.e. the last frame in the history).
    """
    total_loss = 0.0
    count = 0
    for inputs, targets in loader:
        # inputs shape: [batch, L, 20], targets shape: [batch, 20]
        # Current coefficient is inputs[:, -1, :] (the last time step in input history)
        current = inputs[:, -1, :]
        loss = np.mean((targets.numpy() - current.numpy()) ** 2)
        total_loss += loss * inputs.size(0)
        count += inputs.size(0)
    return total_loss / count


def masked_slope_loss(pred, target, lambda_zern=1e-2, lambda_tem=1e-1):
    """
    Loss for slope completion task.

    pred shape: [batch, 2*nspots].
    target shape: [batch, 2*nspots*2] concatenating [clean_slopes, mask].
    Returns (total_loss, rec_loss, dict_of_components).
    """
    n = pred.shape[1] // 2
    clean = target[:, :2*n]
    mask = target[:, 2*n:]
    inv_mask = 1.0 - mask

    # 1) Masked reconstruction loss on missing entries only
    diff2 = (pred - clean) ** 2
    loss_rec = (inv_mask * diff2).sum() / (inv_mask.sum() + 1e-8)

    # 2) Temporal smoothness: small L2 penalty that keeps output bounded.
    loss_tem = (pred ** 2).mean() * 1e-6

    # 3) Zernike-consistency proxy: soft Laplacian-smoothness on the slope field.
    #    Scale-insensitive: normalise by mean squared clean-slope magnitude so
    #    the regulariser does not dominate the physically large raw shifts.
    dx = pred[:, :n]
    dy = pred[:, n:]
    clean_dx = clean[:, :n]
    clean_dy = clean[:, n:]
    scale2 = ((clean_dx ** 2).mean() + (clean_dy ** 2).mean()).item()
    lap = ((dx[:, 1:] - dx[:, :-1]) ** 2).mean() + ((dy[:, 1:] - dy[:, :-1]) ** 2).mean()
    loss_zern = lap / (scale2 + 1.0)

    total = loss_rec + lambda_zern * loss_zern + lambda_tem * loss_tem
    return total, loss_rec, {"zern_proxy": loss_zern.item(), "tem": loss_tem.item()}


class ZernikeConsistencyLoss(nn.Module):
    """
    Differentiable Zernike-projection regulariser for slope completion.

    Given a modal derivative matrix Zprime (2*nspots x nmodes) and its
    pseudo-inverse Zprime_pinv (nmodes x 2*nspots), project the predicted
    slopes onto the Zernike derivative basis and penalise the residual.
    """
    def __init__(self, Zprime, Zprime_pinv, rcond=1e-4):
        super().__init__()
        # Register as buffers so they move with the model device
        self.register_buffer('Zprime', torch.tensor(Zprime, dtype=torch.float32))
        self.register_buffer('Zprime_pinv', torch.tensor(Zprime_pinv, dtype=torch.float32))
        self.rcond = rcond

    def forward(self, slopes):
        # slopes: [batch, 2*nspots]
        a = torch.matmul(slopes, self.Zprime_pinv.t())  # [batch, nmodes]
        s_z = torch.matmul(a, self.Zprime.t())           # [batch, 2*nspots]
        return torch.mean((slopes - s_z) ** 2)


def noll_to_nm(j):
    """Convert Noll index j (1-based) to radial order n and azimuthal frequency m."""
    if j == 1:
        return 0, 0
    current_j = 2
    for n in range(1, 100):
        for m in range(n % 2, n + 1, 2):
            if m == 0:
                if current_j == j:
                    return n, 0
                current_j += 1
            else:
                if current_j % 2 == 1:
                    if current_j == j:
                        return n, -m
                    if current_j + 1 == j:
                        return n, m
                else:
                    if current_j == j:
                        return n, m
                    if current_j + 1 == j:
                        return n, -m
                current_j += 2


def main():
    parser = argparse.ArgumentParser(description="Train Phase 5 sequential models for Project RIPRA")
    parser.add_argument("--task", type=str, default="predict", choices=["predict", "classify", "parameter", "complete_slopes"], help="Sequence task to train")
    parser.add_argument("--epochs", type=int, default=10, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=128, help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--lookback", type=int, default=10, help="History window length in frames")
    parser.add_argument("--step", type=int, default=1, help="Future prediction steps ahead (for predict task)")
    parser.add_argument("--dataset", type=str, default="data_ai/dataset.npz", help="Dataset path")
    parser.add_argument("--out_dir", type=str, default="ml_checkpoints/kaggle", help="Output checkpoints folder")
    parser.add_argument("--lambda_zern", type=float, default=1e-2, help="Zernike-consistency regularizer weight")
    parser.add_argument("--lambda_tem", type=float, default=1e-1, help="Temporal smoothness regularizer weight")
    parser.add_argument("--nspots", type=int, default=None, help="Number of sub-apertures (default: infer from dataset)")
    args = parser.parse_args()
    
    # Configure UTF-8 encoding for Windows console printing
    try:
        import sys
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except AttributeError:
        pass

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using execution device: {device}")

    if not os.path.exists(args.dataset):
        print(f"Error: {args.dataset} not found. Please download it or generate one first.")
        return

    # Infer nspots from dataset if not provided
    data_shape = np.load(args.dataset)['displacements'].shape
    nspots = args.nspots if args.nspots is not None else data_shape[1] // 2

    # 1. Load dataset
    print(f"Loading sequence dataset for task '{args.task}' (lookback={args.lookback}, step={args.step})...")
    full_dataset = SHSequenceDataset(args.dataset, lookback=args.lookback, step=args.step, task=args.task)

    # Train / Val / Test split (80% / 10% / 10%) at sequence level
    train_set, val_set, test_set = SHSequenceDataset.split_by_sequence(
        full_dataset, train_ratio=0.8, val_ratio=0.1, seed=42
    )

    # Guard empty splits (tiny datasets) to keep DataLoader happy
    if len(train_set) == 0:
        print("Error: training split is empty (dataset too small for lookback + seq split).")
        return
    if len(val_set) == 0:
        val_set = train_set  # reuse train for validation in tiny configs
    if len(test_set) == 0:
        test_set = val_set

    train_loader = DataLoader(train_set, batch_size=min(args.batch_size, len(train_set)), shuffle=True)
    val_loader = DataLoader(val_set, batch_size=min(args.batch_size, max(1, len(val_set))), shuffle=False)
    test_loader = DataLoader(test_set, batch_size=min(args.batch_size, max(1, len(test_set))), shuffle=False)

    print(f"Dataset split: Train={len(train_set)}, Val={len(val_set)}, Test={len(test_set)}")

    # 2. Setup model and loss criterion
    if args.task == 'predict':
        model = WavefrontLSTM(input_dim=20, hidden_dim=128, output_dim=20)
        criterion = nn.MSELoss()
    elif args.task == 'classify':
        model = TurbulenceClassifierLSTM(input_dim=20, hidden_dim=64, num_classes=3)
        criterion = nn.CrossEntropyLoss()
    elif args.task == 'parameter':
        model = TurbulenceParameterEstimator(input_dim=2*nspots, hidden_dim=128, output_dim=1)
        criterion = nn.MSELoss()
    elif args.task == 'complete_slopes':
        model = SlopeCompletionLSTM(nspots=nspots, hidden_dim=128, num_layers=2)
        zern_loss_obj = None
        zern_loss_available = False
        try:
            import scipy.linalg as la
            # Build Zprime from the first frame's clean slopes by solving
            # min ||Zprime * coeffs - clean|| using SVD (matches recon.c rcond).
            import pandas as pd
            import importlib.util
            base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            gen_path = os.path.join(base, 'tools', 'generate_dataset.py')
            spec = importlib.util.spec_from_file_location("generate_dataset", gen_path)
            gds = importlib.util.module_from_spec(spec)
            sys.modules["generate_dataset"] = gds
            spec.loader.exec_module(gds)
            zernike_derivatives = gds.zernike_derivatives
            load_system_config_local = gds.load_system_config
            cfg = load_system_config_local(os.path.join(base, 'config', 'system.conf'))
            spots_csv = os.path.join(base, 'results', 'reference_centroids_c.csv')
            spots_df = pd.read_csv(spots_csv)
            nmax = int(cfg['zernike_nmax'])
            max_j = (nmax + 1) * (nmax + 2) // 2
            nmodes = max_j - 1
            nspots_ds = len(spots_df)
            M = 15
            rbar = cfg['sa_radius'] / cfg['pupil_radius']
            kk = cfg['pupil_radius'] / (np.pi * cfg['sa_radius'] ** 2)
            mean_cx = spots_df['ref_cx'].mean()
            mean_cy = spots_df['ref_cy'].mean()
            Zprime = np.zeros((2 * nspots_ds, nmodes))
            modes = []
            for idx in range(nmodes):
                j = idx + 2
                n, m = noll_to_nm(j)
                modes.append((j, n, m))
            for k in range(nspots_ds):
                x_c = (spots_df.loc[k, 'ref_cx'] - mean_cx) * cfg['camera_pixsize'] / cfg['pupil_radius']
                y_c = -(spots_df.loc[k, 'ref_cy'] - mean_cy) * cfg['camera_pixsize'] / cfg['pupil_radius']
                for m_idx, (j, n, m) in enumerate(modes):
                    sum_dzdx = 0.0
                    sum_dzdy = 0.0
                    count = 0
                    for rs in range(M):
                        dy = -rbar + 2.0 * rbar * rs / (M - 1)
                        for cs in range(M):
                            dx = -rbar + 2.0 * rbar * cs / (M - 1)
                            if dx * dx + dy * dy <= rbar * rbar:
                                dzx, dzy = zernike_derivatives(n, m, x_c + dx, y_c + dy)
                                sum_dzdx += dzx
                                sum_dzdy += dzy
                                count += 1
                    avg_dzdx = sum_dzdx / count if count else 0.0
                    avg_dzdy = sum_dzdy / count if count else 0.0
                    Zprime[k, m_idx] = kk * avg_dzdx
                    Zprime[k + nspots_ds, m_idx] = -kk * avg_dzdy
            Zprime_pinv = la.pinv(Zprime, rtol=1e-4)
            zern_loss_obj = ZernikeConsistencyLoss(Zprime, Zprime_pinv)
            zern_loss_available = True
        except Exception as e:
            print(f"  Note: Zernike consistency regulariser unavailable ({e}), using Laplacian proxy.")
            zern_loss_obj = None

        def complete_loss(pred, target):
            n = pred.shape[1] // 2
            clean = target[:, :2 * n]
            mask = target[:, 2 * n:]
            inv_mask = 1.0 - mask
            diff2 = (pred - clean) ** 2
            loss_rec = (inv_mask * diff2).sum() / (inv_mask.sum() + 1e-8)
            loss_tem = (pred ** 2).mean() * 1e-6
            if zern_loss_available and zern_loss_obj is not None:
                loss_zern = zern_loss_obj(pred)
            else:
                dx = pred[:, :n]
                dy = pred[:, n:]
                loss_zern = ((dx[:, 1:] - dx[:, :-1]) ** 2).mean() + ((dy[:, 1:] - dy[:, :-1]) ** 2).mean()
            total = loss_rec + args.lambda_zern * loss_zern + args.lambda_tem * loss_tem
            return total, loss_rec, {"zern": loss_zern.item() if torch.is_tensor(loss_zern) else float(loss_zern), "tem": loss_tem.item()}

        criterion = complete_loss

    model = model.to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)

    os.makedirs(args.out_dir, exist_ok=True)
    best_val_loss = float("inf")

    print(f"\nStarting training for {args.epochs} epochs...")
    for epoch in range(args.epochs):
        if args.task == 'complete_slopes':
            train_loss = train_epoch_complete(model, train_loader, criterion, optimizer, device)
            val_loss = evaluate(model, val_loader, criterion, device, task='complete_slopes')
        else:
            train_loss = train_epoch(model, train_loader, criterion, optimizer, device)
            val_loss = evaluate(model, val_loader, criterion, device)
        scheduler.step()

        print(f"Epoch {epoch+1:02d}/{args.epochs:02d} | Train Loss: {train_loss:.6f} | Val Loss: {val_loss:.6f}")

        if val_loss < best_val_loss or args.task == 'complete_slopes':
            best_val_loss = val_loss
            checkpoint_path = os.path.join(args.out_dir, f"best_sequence_{args.task}.pt")
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_loss': val_loss,
                'nspots': nspots,
                'lookback': args.lookback,
            }, checkpoint_path)

    # 3. Final evaluation
    checkpoint_path = os.path.join(args.out_dir, f"best_sequence_{args.task}.pt")
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()

    test_loss = evaluate(model, test_loader, criterion, device, task=args.task)
    print(f"\nFinal Test Loss on Best Checkpoint: {test_loss:.6f}")

    # Post-training task-specific analysis
    if args.task == 'predict':
        # Evaluate against persistence baseline on test set
        # persistence loader needs to use CPU and raw tensors
        test_loader_cpu = DataLoader(test_set, batch_size=args.batch_size, shuffle=False)
        persistence_mse = run_persistence_baseline(test_loader_cpu, args.step)
        print(f"Persistence Baseline Test MSE: {persistence_mse:.6f}")
        improvement = (persistence_mse - test_loss) / persistence_mse * 100
        print(f"LSTM Improvement over Persistence: {improvement:.2f}%")

        # Spot check single sequence prediction
        with torch.no_grad():
            inputs, targets = next(iter(test_loader))
            inputs = inputs.to(device)
            preds = model(inputs).cpu().numpy()
            targets = targets.numpy()
            print("\nWavefront Prediction Spot Check (First 3 modes of sample 1):")
            print(f"  True future: {targets[0][:3]}")
            print(f"  LSTM Pred:   {preds[0][:3]}")
            print(f"  Persistence: {inputs[0, -1, :3].cpu().numpy()}")

    elif args.task == 'classify':
        # Compute accuracy
        correct = 0
        total = 0
        with torch.no_grad():
            for inputs, targets in test_loader:
                inputs, targets = inputs.to(device), targets.to(device)
                outputs = model(inputs)
                preds = torch.argmax(outputs, dim=1)
                correct += (preds == targets).sum().item()
                total += targets.size(0)
        accuracy = correct / total * 100
        print(f"Turbulence Classification Test Accuracy: {accuracy:.2f}%")

    elif args.task == 'parameter':
        # Compute R-squared correlation
        all_targets = []
        all_preds = []
        with torch.no_grad():
            for inputs, targets in test_loader:
                inputs = inputs.to(device)
                outputs = model(inputs).squeeze(1)
                all_targets.extend(targets.numpy())
                all_preds.extend(outputs.cpu().numpy())
        all_targets = np.array(all_targets)
        all_preds = np.array(all_preds)

        # R2 calculation
        y_mean = np.mean(all_targets)
        ss_tot = np.sum((all_targets - y_mean) ** 2)
        ss_res = np.sum((all_targets - all_preds) ** 2)
        r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0.0
        print(f"Turbulence Parameter (D/r_0) Regression R^2 Score: {r2:.4f}")
        print(f"Average target D/r_0: {np.mean(all_targets):.2f}, RMSE: {np.sqrt(np.mean((all_targets - all_preds) ** 2)):.4f}")

    elif args.task == 'complete_slopes':
        # Evaluate masked RMSE and spatial-interpolation baseline on test set
        test_loader_cpu = DataLoader(test_set, batch_size=args.batch_size, shuffle=False)
        total_masked_se = 0.0
        total_nn_masked_se = 0.0
        total_masked_count = 0
        with torch.no_grad():
            for inputs, targets in test_loader_cpu:
                # inputs: [batch, L+1, 4*nspots], targets: [batch, 2*nspots*2]
                x = inputs.to(device)
                preds = model(x).cpu().numpy()         # [batch, 2*nspots]
                clean = targets[:, :2*nspots].numpy()
                mask = targets[:, 2*nspots:].numpy()
                inv_mask = 1.0 - mask

                # Masked squared error for model
                se = ((preds - clean) ** 2) * inv_mask
                total_masked_se += se.sum()
                total_masked_count += inv_mask.sum()

                # Nearest-neighbour baseline: use last valid frame in window
                # (simplified spatial interpolation baseline: copy from nearest valid spot
                # in the *same* frame using Euclidean centroid distance)
                for b in range(clean.shape[0]):
                    valid = mask[b] > 0.5
                    for k in range(2*nspots):
                        if not valid[k]:
                            # Simple copy from nearest valid by index distance
                            left = k - 1
                            while left >= 0 and not valid[left]:
                                left -= 1
                            right = k + 1
                            while right < 2*nspots and not valid[right]:
                                right += 1
                            best = clean[b, left] if left >= 0 and (right >= 2*nspots or k - left <= right - k) else clean[b, right]
                            total_nn_masked_se += (best - clean[b, k]) ** 2

        rmse_model = np.sqrt(total_masked_se / total_masked_count) if total_masked_count else 0.0
        rmse_nn = np.sqrt(total_nn_masked_se / total_masked_count) if total_masked_count else 0.0
        ratio = rmse_model / rmse_nn if rmse_nn > 0 else 0.0
        print(f"\nMasked Slope Completion Test RMSE: {rmse_model:.4f} px")
        print(f"Nearest-Neighbour Baseline RMSE:    {rmse_nn:.4f} px")
        print(f"Model / Baseline ratio:             {ratio:.2%}")

        # Spot check
        with torch.no_grad():
            inputs, targets = next(iter(test_loader))
            inputs = inputs.to(device)
            preds = model(inputs).cpu().numpy()
            clean = targets[:, :2*nspots].numpy()
            mask = targets[:, 2*nspots:].numpy()
            print("\nSlope Completion Spot Check (sample 1, first 6 spots):")
            print(f"  True dx:  {clean[0, :6]}")
            print(f"  Pred dx:  {preds[0, :6]}")
            print(f"  Mask:     {mask[0, :6].astype(int)}")

if __name__ == "__main__":
    main()
