/*
 * tests/doc_example.c - Public API worked example
 *
 * Demonstrates the full RIPPA pipeline using only the public C API
 * (rippra_api.h).  Requires synthetic test data generated by
 *   python ml/synthetic_shwfs.py
 * in the rippra/ directory.
 *
 * Build: cc doc_example.c -lrippra -lm -o doc_example
 * Run:   ./doc_example
 */

#include "rippra/rippra_api.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

static double *load_raw(const char *path, int n)
{
    double *buf = (double *)malloc(n * sizeof(double));
    if (!buf) return NULL;
    FILE *fp = fopen(path, "rb");
    if (!fp) { free(buf); return NULL; }
    size_t got = fread(buf, sizeof(double), n, fp);
    fclose(fp);
    if (got != (size_t)n) { free(buf); return NULL; }
    return buf;
}

int main(void)
{
    int pass = 0, total = 0;

    /* Step 0: default config */
    rippra_api_config cfg = rippra_default_config();
    printf("Config: %dx%d, totlenses=%d, zernike_nmax=%d\n",
           cfg.frame_width, cfg.frame_height,
           cfg.totlenses, cfg.zernike_nmax);

    int npix = cfg.frame_width * cfg.frame_height;

    /* Step 1: load flat frame and calibrate */
    double *flat = load_raw("data_raw/sh_flat.raw", npix);
    if (!flat) {
        printf("SKIP: data_raw/sh_flat.raw not found\n");
        return 0;
    }
    total++; pass++;

    void *cal = rippra_calibrate(flat, cfg.frame_width,
                                  cfg.frame_height, &cfg);
    free(flat);
    if (!cal) {
        printf("FAIL: rippra_calibrate returned NULL\n");
        return 1;
    }
    total++; pass++;
    printf("Calibration handle created\n");

    int nspots = rippra_calibration_nspots(cal);
    total++; pass += (nspots > 0);
    printf("Detected %d spots\n", nspots);

    /* Check reference centroids are readable */
    double *ref_cx = (double *)malloc(nspots * sizeof(double));
    double *ref_cy = (double *)malloc(nspots * sizeof(double));
    rippra_calibration_ref_centroids(cal, ref_cx, ref_cy);
    total++; pass += (isfinite(ref_cx[0]) && isfinite(ref_cy[0]));
    free(ref_cx); free(ref_cy);

    /* Step 2: load aberrated frame and compute centroids */
    double *frame = load_raw("data_raw/img.raw", npix);
    if (!frame) {
        rippra_calibration_free(cal);
        printf("SKIP: data_raw/img.raw not found\n");
        return 0;
    }
    total++; pass++;

    double *dx = (double *)calloc(nspots, sizeof(double));
    double *dy = (double *)calloc(nspots, sizeof(double));
    int    *mask = (int *)calloc(nspots, sizeof(int));

    int ret = rippra_centroid(cal, frame, cfg.frame_width,
                               cfg.frame_height, dx, dy, mask);
    free(frame);
    total++; pass += (ret == 0);
    printf("Centroid ret=%d\n", ret);

    /* Step 3: query nnodes and do zonal reconstruction */
    int nnodes = rippra_calibration_nnodes(cal);
    total++; pass += (nnodes > 0);
    printf("Phase grid has %d nodes\n", nnodes);

    double *phase = (double *)calloc(nnodes, sizeof(double));
    ret = rippra_reconstruct_zonal(cal, dx, dy, mask, &cfg, phase);
    total++; pass += (ret == 0);
    printf("Zonal recon ret=%d\n", ret);

    /* Step 4: modal reconstruction */
    int nmodes = (cfg.zernike_nmax + 1) * (cfg.zernike_nmax + 2) / 2;
    double *coeffs = (double *)calloc(nmodes, sizeof(double));
    ret = rippra_reconstruct_modal(cal, dx, dy, mask, &cfg, coeffs);
    total++; pass += (ret == 0);
    printf("Modal recon ret=%d, nmodes=%d\n", ret, nmodes);

    /* Step 5: turbulence characterization (build multi-frame series) */
    int nf = 5;
    double *dx_series = (double *)malloc(nf * nspots * sizeof(double));
    double *dy_series = (double *)malloc(nf * nspots * sizeof(double));
    for (int fi = 0; fi < nf; fi++)
        for (int si = 0; si < nspots; si++) {
            dx_series[fi * nspots + si] = dx[si] * (1.0 + 0.1 * fi);
            dy_series[fi * nspots + si] = dy[si] * (1.0 + 0.1 * fi);
        }
    double r0 = rippra_compute_r0(dx_series, dy_series, nf, nspots, &cfg);
    double tau0 = rippra_compute_tau0(dx_series, dy_series, nf, nspots, 1000.0);
    free(dx_series); free(dy_series);
    total++; pass += (isfinite(r0) && r0 > 0);
    total++; pass += (isfinite(tau0) && tau0 > 0);
    printf("r0 = %.6f m, tau0 = %.6f s\n", r0, tau0);

    /* Step 6: full pipeline (centroid + modal in one call) */
    double *p_dx = (double *)calloc(nspots, sizeof(double));
    double *p_dy = (double *)calloc(nspots, sizeof(double));
    int    *p_mask = (int *)calloc(nspots, sizeof(int));
    double *p_coeffs = (double *)calloc(nmodes, sizeof(double));

    frame = load_raw("data_raw/img.raw", npix);
    if (frame) {
        ret = rippra_process_frame(cal, frame, cfg.frame_width,
                                    cfg.frame_height, &cfg,
                                    p_dx, p_dy, p_mask, p_coeffs);
        total++; pass += (ret == 0);
        printf("process_frame ret=%d\n", ret);
        free(frame);
    }
    free(p_dx); free(p_dy); free(p_mask); free(p_coeffs);

    /* Step 7: DM mapping */
    double *dm_cmds = (double *)calloc(nnodes, sizeof(double));
    ret = rippra_dm_map(phase, nnodes, cal, &cfg, dm_cmds);
    total++; pass += (ret == 0);
    printf("DM map ret=%d\n", ret);

    /* Step 8: DM apply */
    double *residual = (double *)calloc(nnodes, sizeof(double));
    ret = rippra_dm_apply(dm_cmds, nnodes, cal, &cfg,
                           phase, residual);
    total++; pass += (ret == 0);

    /* Step 9: closed-loop step (returns RMS in µrad on success) */
    ret = rippra_closed_loop_step(cal, phase, nnodes,
                                   &cfg, dm_cmds, 0.5);
    total++; pass += (ret >= 0);
    printf("Closed-loop step ret=%d (residual RMS %.3f µrad)\n", ret, ret * 1.0);

    /* Step 10: Strehl ratio */
    double strehl = rippra_strehl_ratio(phase, nnodes);
    total++; pass += (strehl > 0.0 && strehl <= 1.0);
    printf("Strehl ratio = %.4f\n", strehl);

    /* Cleanup */
    free(dx); free(dy); free(mask);
    free(phase); free(coeffs); free(dm_cmds); free(residual);
    rippra_calibration_free(cal);

    printf("\n%d / %d checks passed\n", pass, total);
    return (pass == total) ? 0 : 1;
}
